AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  imdb-serverless-etl

  Serverless data pipeline for IMDb movie data enrichment, demonstrating
  the Medallion Architecture. Permissions are granted to read the OMDb API Key
  from a manually managed Secrets Manager secret.

Parameters:
  BronzeBucketName:
    Type: String
    Description: "Name of the Bronze S3 Bucket"
  SilverBucketName:
    Type: String
    Description: "Name of the Silver S3 Bucket"
  GoldBucketName:
    Type: String
    Description: "Name of the Gold S3 Bucket"

Resources:
  # S3 Buckets
  BronzeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BronzeBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SilverBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SilverBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  GoldBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref GoldBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # SQS Queue: Queue to decouple Lambda functions
  ImdbMovieQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: imdb-movie-queue.fifo
      FifoQueue: true
      VisibilityTimeout: 60
      MessageRetentionPeriod: 86400
      ReceiveMessageWaitTimeSeconds: 5

  # IAM Role for Lambda Function 1 (GetMoviesAndSendToQueueFunction)
  GetMoviesAndSendToQueueLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SQSWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt ImdbMovieQueue.Arn

  # Lambda Function 1: GetMoviesAndSendToQueueFunction
  GetMoviesAndSendToQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetMoviesAndSendToQueue
      Description: Fetches top movies from IMDb and sends them to SQS.
      Handler: fetch_top_movies.lambda_handler
      Runtime: python3.13
      Timeout: 60
      MemorySize: 128
      CodeUri: lambdas/fetch_top_movies/
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ImdbMovieQueue
          IMDB_DATA_URL: https://top-movies.s3.eu-central-1.amazonaws.com/Top250Movies.json
          MAX_RETRIES: "3"
          BASE_DELAY_SECONDS: "1"
      Role: !GetAtt GetMoviesAndSendToQueueLambdaRole.Arn
      Events:
        DailyScheduler:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)
            Enabled: true
            Input: '{"top_n": 10, "batch_size": 1}'

  # IAM Role for Lambda Function 2 (EnrichAndStoreMovieFunction)
  EnrichAndStoreMovieLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3WriteAndSQSReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref BronzeBucket, '/bronze/*']]
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt ImdbMovieQueue.Arn
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/imdb-etl/omdb-api-key-*"

  # Lambda Function 2: EnrichAndStoreMovieFunction
  EnrichAndStoreMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EnrichAndStoreMovie
      Description: Enriches movie data from SQS and stores it in S3 (Bronze Layer).
      Handler: enrich_and_store_movie.lambda_handler
      Runtime: python3.13
      Timeout: 60
      MemorySize: 128
      CodeUri: lambdas/enrich_and_store_movies/
      Environment:
        Variables:
          OMDB_API_SECRET_NAME: /imdb-etl/omdb-api-key 
          TARGET_S3_BUCKET: !Ref BronzeBucket
          OMDB_URL: https://www.omdbapi.com/
          MAX_RETRIES: "3"
          BASE_DELAY_SECONDS: "1"
      Role: !GetAtt EnrichAndStoreMovieLambdaRole.Arn
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt ImdbMovieQueue.Arn
            BatchSize: 1

  # IAM Role for Lambda Function 3 (ProcessBronzeToSilverFunction)
  ProcessBronzeToSilverLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ProcessBronzeToSilverS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Join ['', ['arn:aws:s3:::', !Ref BronzeBucket]]
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref BronzeBucket, '/bronze/*']]
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref SilverBucket, '/silver/*']]

# Lambda Function 3: ProcessBronzeToSilverFunction
  ProcessBronzeToSilverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProcessBronzeToSilver
      Description: Triggered when _success is created in bronze/, converts to silver.
      CodeUri: lambdas/process_bronze_to_silver/
      Handler: process_bronze_to_silver.lambda_handler
      Runtime: python3.13
      Timeout: 60
      MemorySize: 256
      Role: !GetAtt ProcessBronzeToSilverLambdaRole.Arn
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python313:3
      Environment:
        Variables:
          MAX_RETRIES: "3"
          BASE_DELAY_SECONDS: "1"
          S3_BUCKET_SOURCE: !Ref BronzeBucketName
          S3_BUCKET_TARGET: !Ref SilverBucketName

  # IAM Role for Lambda Function 4 (ProcessSilverToGoldFunction)
  ProcessSilverToGoldLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ProcessBronzeToSilverS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Join ['', ['arn:aws:s3:::', !Ref SilverBucket]]
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref SilverBucket, '/silver/*']]
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref GoldBucket, '/gold/*']]

  # Lambda Function 4: ProcessSilverToGoldFunction
  ProcessSilverToGoldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProcessSilverToGold
      Description: Triggered when file is created in silver/, converts to gold.
      CodeUri: lambdas/process_silver_to_gold/
      Handler: process_silver_to_gold.lambda_handler
      Runtime: python3.13
      Timeout: 60
      MemorySize: 256
      Role: !GetAtt ProcessSilverToGoldLambdaRole.Arn
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python313:3
      Environment:
        Variables:
          MAX_RETRIES: "3"
          BASE_DELAY_SECONDS: "1"
          S3_BUCKET_SOURCE: !Ref SilverBucketName
          S3_BUCKET_TARGET: !Ref GoldBucketName

Outputs:
  BronzeBucketName:
    Description: "Name of the Bronze S3 Bucket"
    Value: !Ref BronzeBucketName
    Export:
      Name: "IMDB-BronzeBucketName"
  SilverBucketName:
    Description: "Name of the Silver S3 Bucket"
    Value: !Ref SilverBucketName
    Export:
      Name: "IMDB-SilverBucketName"
  GoldBucketName:
    Description: "Name of the Gold S3 Bucket"
    Value: !Ref GoldBucketName
    Export:
      Name: "IMDB-GoldBucketName"
  GetMoviesAndSendToQueueFunctionArn:
    Description: "ARN of the GetMoviesAndSendToQueue Lambda Function"
    Value: !GetAtt GetMoviesAndSendToQueueFunction.Arn
    Export:
      Name: "IMDB-GetMoviesAndSendToQueueFunctionArn"
  EnrichAndStoreMovieFunctionArn:
    Description: "ARN of the EnrichAndStoreMovie Lambda Function"
    Value: !GetAtt EnrichAndStoreMovieFunction.Arn
    Export:
      Name: "IMDB-EnrichAndStoreMovieFunctionArn"
  ProcessBronzeToSilverFunctionArn:
    Description: "ARN of the ProcessBronzeToSilver Lambda Function"
    Value: !GetAtt ProcessBronzeToSilverFunction.Arn
    Export:
      Name: "IMDB-ProcessBronzeToSilverFunctionArn"
  ProcessSilverToGoldFunctionArn:
    Description: "ARN of the ProcessSilverToGold Lambda Function"
    Value: !GetAtt ProcessSilverToGoldFunction.Arn
    Export:
      Name: "IMDB-ProcessSilverToGoldFunctionArn"
  
